### ISSUE TITLE
How to authenticate

### ISSUE THREAD

**Issue by zuhairabid** [0xE666/Soundmap-API#1]
Hello can you help me in getting authenticated using this python script and then use it ? thanks

**Comment by 0xE666** [comment]
in the read me,

Configuring an iOS Device for Burp Suite
To configure your iOS device to work with Burp Suite, follow these steps:

Install Burp Suite: Download and install Burp Suite on your computer from the [official website](https://portswigger.net/burp).

Configure Burp Suite Proxy:

Open Burp Suite and go to the "Proxy" tab.
Click on "Options" and ensure the interface is set to listen on 127.0.0.1:8080 (or another desired port).
Configure iOS Device to Use Burp as a Proxy:

On your iOS device, go to Settings > Wi-Fi.
Tap the icon next to the connected Wi-Fi network.
Scroll down to HTTP Proxy and select Manual.
Enter your computer's IP address in the Server field and 8080 (or the port set in Burp) in the Port field.
Install Burp Suite CA Certificate on iOS:

Open Safari on your iOS device and navigate to http://burp (or http://<your-computer-ip>:<port>).
Download the CA certificate and follow the prompts to install it.
Go to Settings > General > Profile (or Profile & Device Management) to install the certificate.
Enable full trust for the Burp Suite certificate under Settings > General > About > Certificate Trust Settings.
Start Intercepting Traffic:

Go back to Burp Suite, ensure intercept is on in the "Proxy" > "Intercept" tab.
Browse on your iOS device, and you should see traffic being captured in Burp Suite.
For detailed instructions and troubleshooting, refer to the [Burp Suite documentation](https://portswigger.net/burp/documentation/desktop/mobile/config-ios-device).
